"""Notes database - Data access layer for users_notes using Supabase HTTP API."""
from typing import Optional, List, Dict, Any
from datetime import datetime
from uuid import UUID

from src.utils.logger import get_logger
from src.utils.supabase_client import SupabaseClient


class NotesDatabase:
    """Database layer for user notes (users_notes table)."""

    TABLE = "users_notes"

    def __init__(self):
        """Initialize the database connection."""
        self.logger = get_logger(__name__)
        self.client = SupabaseClient.get_instance()
        self.logger.info("NotesDatabase initialized successfully (using Supabase HTTP API)")

    def _validate_uuid(self, value: str) -> Optional[str]:
        """Validate and return UUID string."""
        self.logger.debug(f"_validate_uuid called with value={value}")
        try:
            UUID(value)
            return value
        except (ValueError, TypeError):
            self.logger.error(f"Invalid UUID format: {value}")
            return None

    async def list_notes(self, userPublicId: str) -> List[Dict[str, Any]]:
        """List all non-deleted notes for a user, ordered by updated_at desc."""
        self.logger.debug(f"list_notes called for userPublicId={userPublicId}")
        user_uuid = self._validate_uuid(userPublicId)
        if not user_uuid:
            return []

        try:
            rows = await self.client.select(
                table=self.TABLE,
                columns="id,user_id,reference,normalized_reference,content,tags,folder_id,created_at,updated_at",
                filters={"user_id": user_uuid, "deleted_at": "is.null"},
                order="updated_at.desc",
            )
            self.logger.info(f"list_notes returned {len(rows)} notes for user {userPublicId}")
            return rows
        except Exception as e:
            self.logger.error(f"Error in list_notes: {e}", exc_info=True)
            raise

    async def get_note_by_id(self, noteId: str, userPublicId: str) -> Optional[Dict[str, Any]]:
        """Get a single note by id (UUID) and user (non-deleted)."""
        self.logger.debug(f"get_note_by_id called noteId={noteId}, userPublicId={userPublicId}")
        user_uuid = self._validate_uuid(userPublicId)
        if not user_uuid or not self._validate_uuid(noteId):
            return None

        try:
            rows = await self.client.select(
                table=self.TABLE,
                columns="id,user_id,reference,normalized_reference,content,tags,folder_id,created_at,updated_at",
                filters={"id": noteId, "user_id": user_uuid, "deleted_at": "is.null"},
            )
            if not rows:
                self.logger.warning(f"Note not found: id={noteId}, userPublicId={userPublicId}")
                return None
            return rows[0]
        except Exception as e:
            self.logger.error(f"Error in get_note_by_id: {e}", exc_info=True)
            raise

    async def create_note(
        self,
        userPublicId: str,
        reference: str,
        normalized_reference: Optional[str],
        content: str,
        tags: Optional[List[str]] = None,
        folderId: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Insert a new note. id is generated by DB (UUID)."""
        self.logger.debug(f"create_note called for userPublicId={userPublicId}")
        user_uuid = self._validate_uuid(userPublicId)
        if not user_uuid:
            return None

        data = {
            "user_id": user_uuid,
            "reference": reference,
            "content": content,
            "tags": tags if tags is not None else [],
        }
        if normalized_reference is not None:
            data["normalized_reference"] = normalized_reference
        if folderId:
            folder_uuid = self._validate_uuid(folderId)
            if folder_uuid:
                data["folder_id"] = folder_uuid
        # Omit nulls so PostgREST/DB use column defaults and avoid 409 from explicit null

        try:
            row = await self.client.insert(table=self.TABLE, data=data, return_data=True)
            out = row[0] if isinstance(row, list) and row else row
            self.logger.info(f"create_note created note id={out.get('id')} for user {userPublicId}")
            return out
        except Exception as e:
            self.logger.error(f"Error in create_note: {e}", exc_info=True)
            raise

    async def update_note(
        self,
        noteId: str,
        userPublicId: str,
        reference: Optional[str] = None,
        normalized_reference: Optional[str] = None,
        content: Optional[str] = None,
        tags: Optional[List[str]] = None,
        folderId: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Update an existing note (only non-deleted). Sets updated_at to now."""
        self.logger.debug(f"update_note called noteId={noteId}, userPublicId={userPublicId}")
        user_uuid = self._validate_uuid(userPublicId)
        if not user_uuid or not self._validate_uuid(noteId):
            return None

        data = {"updated_at": datetime.utcnow().isoformat() + "Z"}
        if reference is not None:
            data["reference"] = reference
        if normalized_reference is not None:
            data["normalized_reference"] = normalized_reference
        if content is not None:
            data["content"] = content
        if tags is not None:
            data["tags"] = tags
        if folderId is not None:
            data["folder_id"] = self._validate_uuid(folderId) if folderId else None

        try:
            rows = await self.client.update(
                table=self.TABLE,
                data=data,
                filters={"id": noteId, "user_id": user_uuid, "deleted_at": "is.null"},
                return_data=True,
            )
            if not rows:
                self.logger.warning(f"Note not found for update: id={noteId}, userPublicId={userPublicId}")
                return None
            self.logger.info(f"update_note updated note id={noteId}")
            return rows[0]
        except Exception as e:
            self.logger.error(f"Error in update_note: {e}", exc_info=True)
            raise

    async def soft_delete_note(self, noteId: str, userPublicId: str) -> bool:
        """Soft-delete a note by setting deleted_at."""
        self.logger.debug(f"soft_delete_note called noteId={noteId}, userPublicId={userPublicId}")
        user_uuid = self._validate_uuid(userPublicId)
        if not user_uuid or not self._validate_uuid(noteId):
            return False

        data = {"deleted_at": datetime.utcnow().isoformat() + "Z"}

        try:
            rows = await self.client.update(
                table=self.TABLE,
                data=data,
                filters={"id": noteId, "user_id": user_uuid, "deleted_at": "is.null"},
                return_data=True,
            )
            if not rows:
                self.logger.warning(f"Note not found for delete: id={noteId}, userPublicId={userPublicId}")
                return False
            self.logger.info(f"soft_delete_note deleted note id={noteId}")
            return True
        except Exception as e:
            self.logger.error(f"Error in soft_delete_note: {e}", exc_info=True)
            raise
